#!/bin/sh -e

if [ -z "$3" ]; then
  echo "Usage: $0 <sandbox profile> <nix store target> <output directory>"
  exit 1
fi

this=$(realpath "$0")
root=$(dirname "$this")

sandbox_profile=$(realpath "$1")

target=$(realpath "$2")
target_name=$(basename "$target")

output=$(realpath "$3")
mkdir $output; cd $_

for path in $(nix-store -qR "$target"); do
  cp --parents -r "$path" .
done

chmod -R +w nix
mkdir -p etc

cp "$sandbox_profile" etc/profile.sb

install -D "$root/wrapper.sh" "bin/$target_name"
sed -i "s:@TARGET@:$target:" "bin/$target_name"
